---
title: "Organização"
output:
  pdf_document: default
  html_notebook: default
---

Limpeza de dados de armadilhas fotográficas PELD - CCM.

Desenvolvimento: Fernando Lima, D.Sc.

## PREPARAÇÃO

### PACOTES

```{r pacotes, message=FALSE}
rm(list = ls(all = TRUE))
source("../funcoes/pacotes.R")
pacotes("here", "readr", "dplyr", "stringr")
```

### Carregar arquivos

Arquivos baixados da plataforma Wildlife Insights

```{r leitura, warning=FALSE}
cameras <-  readr::read_csv(
  here("01_dadosDeEntrada", "cameras.csv"),
  show_col_types = FALSE)

deployments <-  readr::read_csv(
  here("01_dadosDeEntrada", "deployments.csv"),
  show_col_types = FALSE)

projects <-  readr::read_csv(
  here("01_dadosDeEntrada", "projects.csv"),
  show_col_types = FALSE)

sequences <-  readr::read_csv(
  here("01_dadosDeEntrada", "sequences.csv"),
  show_col_types = FALSE)

timeLapse <- readr::read_csv(
  here("01_dadosDeEntrada", "templatePELDCCM.csv"),
  show_col_types = FALSE)
```

\newpage

### Integrar e organizar informações
```{r}
dados <- deployments %>%
  dplyr::left_join(
    sequences, by = "deployment_id"
    ) %>%
  # filtrar identificações a nível de espécie
  dplyr::filter(
    !is.na(species)
  ) %>%
  # juntar gênero e espécie para nome científico
  dplyr::mutate(
    especie = paste(genus, species)
    ) %>%
  dplyr::mutate(
    placename = substr(deployment_id, 1,4)
  ) %>%
  dplyr::mutate(
    subproject_name = str_replace(subproject_name, "PAISAGEM ", "L")
  )
```

```{r}
timeLapse <- timeLapse[!grepl("Disparo falso", timeLapse$Species),]
timeLapse <- timeLapse[!grepl("Não identificado", timeLapse$Species),]
timeLapse <- timeLapse[!grepl("Disparo falso", timeLapse$Species),]
timeLapse <- timeLapse[!grepl("Não listado", timeLapse$Species),]
timeLapse <- timeLapse[!grepl("Chiroptera", timeLapse$Species),]

timeLapse <- timeLapse %>%
  mutate(
    subproject_name = substr(RelativePath, 1, 3)
  ) %>%
  mutate(
    
  )
sort(unique(timeLapse$Species))
```


```{r}
dados <- dados %>%
  # selecionar dados que o Miltinho pediu
  dplyr::select(
    subproject_name, placename,family,especie
    ) %>%
  # agrupar espécies e plotar número de registros
  dplyr::group_by(
    subproject_name, placename, family, especie
    ) %>%
  dplyr::summarise(
    n = n()
    ) %>%
  # filtrar registros não identificados
  dplyr::filter(
    especie != "No CV Result No CV Result"
    ) %>%
  # renomear
  dplyr::rename(
          ID_Paisagem = subproject_name,
          ID_Sitio = placename,
          Familia = family,
          Especie = especie,
          NuRegistros = n)

#checagem
sort(unique(dados$Especie))

sort(unique(dados$ID_Sitio))

dados$Especie <- gsub("Didelphis marsupialis","Didelphis aurita",
                          dados$Especie)

```

### Exportar arquivos `*.csv`

```{r}
readr::write_csv(dados, here("03_dadosDeSaida", "sinteseCamTrapsPELDCCM.csv"))
```
